### ISSUE TITLE
Fix: connect button UI

### ISSUE THREAD

**Issue by Goodness5** [Custos-Diretriz/Custos-Dapp#38]
- [ ] the connect button should have an avatar
- [ ] Refer to figma design to see the correct version

**Comment by SudiptaPaul-31** [comment]
@Goodness5 Can I work on this

**Comment by Goodness5** [comment]
> @Goodness5 Can I work on this

thanks for your interest but @faytey is currently working on it

**Comment by Pvsaint** [comment]
Can I help please?
